REM INSERTING into SCOTT.JOB_HISTORY
SET DEFINE OFF;
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('102',to_date('13.01.01','DD.MM.RR'),to_date('24.07.06','DD.MM.RR'),'IT_PROG','60');
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('101',to_date('21.09.97','DD.MM.RR'),to_date('27.10.01','DD.MM.RR'),'AC_ACCOUNT','110');
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('101',to_date('28.10.01','DD.MM.RR'),to_date('15.03.05','DD.MM.RR'),'AC_MGR','110');
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('201',to_date('17.02.04','DD.MM.RR'),to_date('19.12.07','DD.MM.RR'),'MK_REP','20');
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('114',to_date('24.03.06','DD.MM.RR'),to_date('31.12.07','DD.MM.RR'),'ST_CLERK','50');
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('122',to_date('01.01.07','DD.MM.RR'),to_date('31.12.07','DD.MM.RR'),'ST_CLERK','50');
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('200',to_date('17.09.95','DD.MM.RR'),to_date('17.06.01','DD.MM.RR'),'AD_ASST','90');
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('176',to_date('24.03.06','DD.MM.RR'),to_date('31.12.06','DD.MM.RR'),'SA_REP','80');
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('176',to_date('01.01.07','DD.MM.RR'),to_date('31.12.07','DD.MM.RR'),'SA_MAN','80');
Insert into SCOTT.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('200',to_date('01.07.02','DD.MM.RR'),to_date('31.12.06','DD.MM.RR'),'AC_ACCOUNT','90');
