--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "SCOTT"."EMPLOYEES" ADD CONSTRAINT "EMP_EMAIL_NN" CHECK ("EMAIL" IS NOT NULL) ENABLE;
 
  ALTER TABLE "SCOTT"."EMPLOYEES" ADD CONSTRAINT "EMP_EMAIL_UK" UNIQUE ("EMAIL") ENABLE;
 
  ALTER TABLE "SCOTT"."EMPLOYEES" ADD CONSTRAINT "EMP_EMP_ID_PK" PRIMARY KEY ("EMPLOYEE_ID") ENABLE;
 
  ALTER TABLE "SCOTT"."EMPLOYEES" ADD CONSTRAINT "EMP_HIRE_DATE_NN" CHECK ("HIRE_DATE" IS NOT NULL) ENABLE;
 
  ALTER TABLE "SCOTT"."EMPLOYEES" ADD CONSTRAINT "EMP_JOB_NN" CHECK ("JOB_ID" IS NOT NULL) ENABLE;
 
  ALTER TABLE "SCOTT"."EMPLOYEES" ADD CONSTRAINT "EMP_LAST_NAME_NN" CHECK ("LAST_NAME" IS NOT NULL) ENABLE;
 
  ALTER TABLE "SCOTT"."EMPLOYEES" ADD CONSTRAINT "EMP_SALARY_MIN" CHECK (salary > 0) ENABLE;
 
  ALTER TABLE "SCOTT"."EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
