--------------------------------------------------------
--  Constraints for Table EVENT_LOG
--------------------------------------------------------

  ALTER TABLE "SCOTT"."EVENT_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EVENT_LOG" MODIFY ("ERROR_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EVENT_LOG" MODIFY ("EVENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EVENT_LOG" MODIFY ("INST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EVENT_LOG" MODIFY ("SID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EVENT_LOG" MODIFY ("SERIAL#" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EVENT_LOG" MODIFY ("LOG_LEVEL" NOT NULL ENABLE);
