--------------------------------------------------------
--  Constraints for Table JOB_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."JOB_HISTORY" ADD CONSTRAINT "JHIST_DATE_INTERVAL" CHECK (end_date > start_date) ENABLE;
 
  ALTER TABLE "SCOTT"."JOB_HISTORY" ADD CONSTRAINT "JHIST_EMPLOYEE_NN" CHECK ("EMPLOYEE_ID" IS NOT NULL) ENABLE;
 
  ALTER TABLE "SCOTT"."JOB_HISTORY" ADD CONSTRAINT "JHIST_EMP_ID_ST_DATE_PK" PRIMARY KEY ("EMPLOYEE_ID", "START_DATE") ENABLE;
 
  ALTER TABLE "SCOTT"."JOB_HISTORY" ADD CONSTRAINT "JHIST_END_DATE_NN" CHECK ("END_DATE" IS NOT NULL) ENABLE;
 
  ALTER TABLE "SCOTT"."JOB_HISTORY" ADD CONSTRAINT "JHIST_JOB_NN" CHECK ("JOB_ID" IS NOT NULL) ENABLE;
 
  ALTER TABLE "SCOTT"."JOB_HISTORY" ADD CONSTRAINT "JHIST_START_DATE_NN" CHECK ("START_DATE" IS NOT NULL) ENABLE;
